name: Sourcegraph LSIF Uploader
description: Upload LSIF data to a Sourcegraph instance
author: Sourcegraph
branding:
  icon: upload
  color: purple

inputs:
  file:
    description: The LSIF dump file to upload
    default: data.lsif
  endpoint:
    description: The URL of the Sourcegraph instance
    default: https://sourcegraph.com
  public_repo_github_token:
    description: The GitHub access token with `public repo` scope (necessary when uploading to Sourcegraph.com, or any Sourcegraph instance with lsifEnforceAuth set to true)
    default: ''

runs:
  using: docker
  image: Dockerfile
  env:
    SRC_ENDPOINT: ${{ inputs.endpoint }}
    PUBLIC_REPO_GITHUB_TOKEN: ${{ inputs.public_repo_github_token }}
  args:
    - ${{ inputs.file }}
