name: Sourcegraph LSIF Uploader
description: Upload LSIF data to a Sourcegraph instance
author: Sourcegraph
branding:
  icon: upload
  color: purple

inputs:
  file:
    description: The LSIF dump file to upload
    default: data.lsif
  endpoint:
    description: The URL of the Sourcegraph instance
    default: https://sourcegraph.com
  github_token:
    description: The GitHub access token with `repo` or `public_repo` scope (necessary when uploading to Sourcegraph.com, or any Sourcegraph instance with `lsifEnforceAuth` set to true)
    default: ''
  ignore_failure:
    description: Exit with code 0, even when the upload fails (prevents a red X from showing up in GitHub pull request checks)
    default: 'false'

runs:
  using: docker
  image: Dockerfile
  env:
    SRC_ENDPOINT: ${{ inputs.endpoint }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    IGNORE_FAILURE: ${{ inputs.ignore_failure }}
  args:
    - ${{ inputs.file }}
